apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "my-first-shipyard"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "deploy"
          tasks:
            - name: "deployment"