apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      requests:
        - url: https://api.github.com/repos/krishnansai/actions/dispatches
          payload: >-
            {"event_type":"run-ping","client_payload":{"command":"ping"}}
          headers:
            - key: Accept
              value: application/vnd.github.v3+json
            - key: Authorization
              value: Bearer {{.env.secret_token_GITTOKEN}}
          method: POST
      envFrom:
        - name: secret_token_GITTOKEN
          secretRef:
            name: token
            key: GIT-TOKEN
      subscriptionID: 4ab21cb2-2324-4a15-8103-d7d1cb331286
      sendFinished: true
      sendStarted: true
