name: linux commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "sai welcome to actions"
      - name : list
        run: |
          sudo apt install apache2
          sudo apache2 start
          curl ifconfig.me
          